# -*- coding: utf-8 -*-
"""ObtenerAICandBIC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18QLQL6AQ--tNZqOfFAYhj3dO4YD62NU2
"""

#ANALIZAR EL VALOR DE AIC ADJUNTANDO EL EXCEL Y PONIENDO COMO X DIFERENTES VARIABLES PARA LUEGO VER EL AIC QUE MEJOR AJUSTE
#https://www.statology.org/aic-in-python/

from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
import pandas as pd

#read in data
#data = pd.read_excel('/content/MODELO7_REGRESION_POLINOMIAL.xlsx')
#data = pd.read_excel('/content/MODELO7_ARBOL_REGRESION.xlsx')
data = pd.read_excel('/content/MODELO7_BOSQUE_ALEATORIO.xlsx')
#print(data)

#define response variable
y = data['ETPF56']

#define predictor variables
# 'Mj/m2/d', 'TMax', 'TMin', 'Viento','PVA', 'MES', 'DiaN' ,
x = data[[ 'ETPF56(-1)', 'ETPF56(-2)', 'ETPF56(-3)', 'ETPF56(-4)', 'ETPF56(-5)', 'ETPF56(-6)', 'ETPF56(-7)']]

#add constant to predictor variables
x = sm.add_constant(x)

#fit regression model
model = sm.OLS(y, x).fit()

#view AIC of model
print(model.aic)

#ANALIZAR EL VALOR DE BIC ADJUNTANDO EL EXCEL Y PONIENDO COMO X DIFERENTES VARIABLES PARA LUEGO VER EL BIC QUE MEJOR AJUSTE
#https://www.statology.org/aic-in-python/

from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
import pandas as pd

#read in data
#data = pd.read_excel('/content/MODELO7_REGRESION_POLINOMIAL.xlsx')
#data = pd.read_excel('/content/MODELO7_ARBOL_REGRESION.xlsx')
data = pd.read_excel('/content/MODELO6_BOSQUE_ALEATORIO.xlsx')
#print(data)

#define response variable
y = data['ETPF56']

#define predictor variables
#  'Mj/m2/d', 'TMax', 'TMin', 'Viento', 'PVA', 'MES', 'DiaN', 
x = data[['ETPF56(-1)', 'ETPF56(-2)', 'ETPF56(-3)', 'ETPF56(-4)', 'ETPF56(-5)', 'ETPF56(-6)', 'ETPF56(-7)']]

#add constant to predictor variables
x = sm.add_constant(x)

#fit regression model
model = sm.OLS(y, x).fit()

#view AIC of model
print(model.bic)